// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adfogztisprrlgjlmozy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkZm9nenRpc3Bycmxnamxtb3p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NDM4MTMsImV4cCI6MjA3MTExOTgxM30.-OjhNBCxu7JySB6Kgwiy4xJuGKHDjKqqCykZ0_J6ZTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});